default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: Jnx
  password: Jnx
  host: localhost
  port: 5432

development:
  <<: *default
  database: newspaper2_development

test:
  <<: *default
  database: newspaper2_test

production:
  <<: *default
  database: newspaper2_production
  username: newspaper2
  password: <%= ENV['NEWSPAPER2_DATABASE_PASSWORD'] %>
